CREATE TABLE users (
    ID INT NOT NULL IDENTITY,
    USERNAME VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    DISPLAY_NAME VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX users_username ON users(USERNAME);
CREATE UNIQUE INDEX users_email ON users(EMAIL);

CREATE TABLE groups (
    ID INT NOT NULL IDENTITY,
    NAME VARCHAR(256) NOT NULL,
    DISPLAY_NAME VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT
);

CREATE UNIQUE INDEX groups_name ON groups(NAME);
