CREATE TABLE users (
    ID INT NOT NULL IDENTITY,
    USERNAME VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    DISPLAY_NAME VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX users_username ON users(USERNAME);
CREATE UNIQUE INDEX users_email ON users(EMAIL);

CREATE TABLE groups (
    ID INT NOT NULL IDENTITY,
    NAME VARCHAR(256) NOT NULL,
    DISPLAY_NAME VARCHAR(256) NOT NULL,
    DESCRIPTION TEXT
);

CREATE UNIQUE INDEX groups_name ON groups(NAME);

CREATE TABLE groups_users (
    GROUP_ID INT NOT NULL,
    USER_ID INT NOT NULL,

    PRIMARY KEY (GROUP_ID,USER_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES groups(ID),
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE UNIQUE INDEX groups_users_uid_gid ON groups_users(USER_ID,GROUP_ID);
